#!/bin/sh

b=0

cc test.c many-many.c lock.c utils.c
while [ $b -lt 10000 ]
do
   b=$((b+1))
   echo "succesfull  executed ",$b," times"
   echo "********************************************************************************"
   ./a.out
   if [ $? -eq 139 ]; then
    exit 1
   fi
done

